/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CacheDialog: typeof import('./src/components/CacheDialog.vue')['default']
    CCComponent: typeof import('./src/components/CCComponent.vue')['default']
    CCNode: typeof import('./src/components/CCNode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    ProfilerPanel: typeof import('./src/components/ProfilerPanel.vue')['default']
    PropItem: typeof import('./src/components/PropItem.vue')['default']
    TreePanel: typeof import('./src/components/TreePanel.vue')['default']
    UserComponent: typeof import('./src/components/UserComponent.vue')['default']
  }
}
